@server_HostAddress = http://localhost:5000

### Add synonym "wash" for "clean"

POST http://localhost:5000/api/synonym
Content-Type: application/json

{
  "word": "clean",
  "synonym": "wash"
}


### Add synonym "tidy" for "wash"

POST http://localhost:5000/api/synonym
Content-Type: application/json

{
  "word": "wash",
  "synonym": "tidy"
}


### Add synonym "neat" for "tidy"
POST http://localhost:5000/api/synonym
Content-Type: application/json

{
  "word": "neat",
  "synonym": "tidy"
}


### Add synonym "rinse" for "tidy"
POST http://localhost:5000/api/synonym
Content-Type: application/json

{
  "word": "tidy",
  "synonym": "well-being"
}


### Get synonyms for "clean"

GET http://localhost:5000/api/synonym/clean
Content-Type: application/json


### Get synonyms for "wash"

GET http://localhost:5000/api/synonym/wash
Content-Type: application/json


### Get synonyms for "tidy"

GET http://localhost:5000/api/synonym/tidy
Content-Type: application/json


### Get synonyms for "rinse"    

GET http://localhost:5000/api/synonym/rinse
Content-Type: application/json

